/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      fontFamily: {
        inter: ['Inter Variable', 'system-ui', 'sans-serif'],
        header: ['Geist Variable', 'system-ui', 'sans-serif'],
        sans: ['Manrope Variable', 'system-ui', 'sans-serif'],
        display: ['Source Serif 4 Variable', 'ui-serif', 'serif'],
        mono: ['ui-monospace', 'monospace'],
        serif: ['Source Serif 4 Variable', 'ui-serif', 'serif'],
      },
    },
  },
  plugins: [require('@tailwindcss/typography'), require('daisyui')],
  daisyui: {
    themes: [
      'light',
      'dark',
      'cupcake',
      'bumblebee',
      'emerald',
      'corporate',
      'synthwave',
      'retro',
      'cyberpunk',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
      'winter',
      'dim',
      'nord',
      'sunset',
    ],
  },
  // darkMode: ['selector', '[data-theme="synthwave"]']
};
